name: V1Z3R CI/CD Pipeline

on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

# Cancel previous runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  YARN_VERSION: '1.22.22'

jobs:
  quality-checks:
    name: Quality & Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build modules
      run: yarn build:modules
      
    - name: Run TypeScript type check
      run: yarn type-check
      
    - name: Run linting
      run: yarn lint
      
    - name: Run tests
      run: yarn test --passWithNoTests --maxWorkers=2
      continue-on-error: false
      
  build:
    name: Build Validation
    runs-on: ubuntu-latest
    needs: quality-checks
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build modules
      run: yarn build:modules
      
    - name: Build application (dev)
      run: yarn build
      env:
        NODE_ENV: production
        
    - name: Build application (static export)
      run: yarn build
      env:
        NODE_ENV: production
        EXPORT_MODE: true