name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '20'
  YARN_VERSION: '1.22.22'

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
        yarn build:modules
        
    - name: Run linting
      run: yarn lint
      
    - name: Run type checking
      run: yarn type-check
      continue-on-error: true  # Allow to continue due to known UI component type issues (Phase 8 priority)
      
    - name: Run stable tests
      run: yarn ci:core-tests
      
    - name: Run unit tests with coverage
      run: yarn test --coverage --maxWorkers=2 --logHeapUsage
      continue-on-error: true  # Allow some test failures while fixing
      
    - name: Run module tests
      run: yarn test:modules
      continue-on-error: true
      
    - name: Build application
      run: yarn build
      env:
        NODE_ENV: production
        EXPORT_MODE: true
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
        yarn build:modules
        
    - name: Install Playwright
      run: npx playwright install --with-deps
      
    - name: Build application
      run: yarn build:dev
      
    - name: Run E2E tests
      run: yarn test:e2e
      
    - name: Upload E2E test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: [test, e2e-test]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
        yarn build:modules
        
    - name: Build for development
      run: yarn build:dev
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
        
    - name: Deploy to S3
      run: |
        aws s3 sync ./out s3://vj-unified-frontend-dev-822063948773 --delete
        
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }} --paths "/*"

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, e2e-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
        yarn build:modules
        
    - name: Build for production
      run: yarn build:prod
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
        
    - name: Deploy to S3
      run: |
        aws s3 sync ./out s3://vj-unified-frontend-prod-822063948773 --delete
        
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} --paths "/*"
        
    - name: Notify deployment
      if: success()
      run: |
        echo "✅ Production deployment successful!"
        echo "🚀 Application is live at: https://v1z3r.sc4pe.net"